services:
  app:
    build: .
    container_name: nebula_ftp
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./staging:/app/staging
      - ./data:/app/data
      - ./Nebula_MonoBot.session:/app/Nebula_MonoBot.session
      - ./nebula.log:/app/nebula.log
      - ./.env:/app/.env
